/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Yuuki
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame(User user) {
        initComponents();
        setLocationRelativeTo(null);
        new Thread() {
            public void run() {
                try {
                    SimpleDateFormat clock = new SimpleDateFormat();
                    Date date = new Date();
                    clock.applyPattern("hh:mm:ss aa");
                    String time = clock.format(date);
                    Thread.sleep(1000);
                    lbClock.setText(time);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }.start();
        String role = user.getRole().toLowerCase();
        switch (role) {
            case "admin":
                jTabbedPane1.addTab("Nhân viên", new NhanVienPanel(user));
                jTabbedPane1.addTab("Phòng ban", new PhongBanPanel(user));
                jTabbedPane1.addTab("Sinh viên", new SinhVienPanel(user));
                jTabbedPane1.addTab("Tài khoản", new UserPanel());
                break;

            case "hr":
                jTabbedPane1.addTab("Nhân viên", new NhanVienPanel(user));
                jTabbedPane1.addTab("Phòng ban", new PhongBanPanel(user));
                jTabbedPane1.addTab("Sinh viên", new SinhVienPanel(user));
                break;

            case "intern":
                jTabbedPane1.addTab("Sinh viên", new SinhVienPanel(user));
                break;

            default:
                JOptionPane.showMessageDialog(this, "Quyền không hợp lệ!");
                System.exit(0);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        lbClock = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Công Ty ISOLF");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 800, 600));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Công Ty ISOLF");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 335, -1));

        lbClock.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lbClock.setText("Time");
        getContentPane().add(lbClock, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 107, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/back1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        User user = new User("admin1", "123456", "admin");

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame(user).setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbClock;
    // End of variables declaration//GEN-END:variables
}
