/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import javax.swing.*;
import Model.*;
import java.sql.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import DAO.*;

/**
 *
 * @author Yuuki
 */
public class NhanVienPanel extends javax.swing.JPanel {

    /**
     * Creates new form nv_panel
     */
    public NhanVienPanel() {
        initComponents();
        hienThiDanhSachNhanVien();
        cb_loai_nv.addActionListener(e -> xuLyLoaiNhanVien());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbNV = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_manv = new javax.swing.JTextField();
        tf_hoten = new javax.swing.JTextField();
        cb_pb = new javax.swing.JComboBox<>();
        cb_loai_nv = new javax.swing.JComboBox<>();
        tf_lcb = new javax.swing.JTextField();
        tf_ds = new javax.swing.JTextField();
        tf_hh = new javax.swing.JTextField();
        tf_ltn = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_tk = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));

        tbNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Họ Tên", "Phòng Ban", "Loại Nhân Viên", "Lương Cơ Bản", "Doanh Số", "Hoa Hồng", "Lương TN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbNV);

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Sắp Xếp");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Tìm Kiếm");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã Nhân Viên");

        jLabel2.setText("Họ Tên");

        jLabel3.setText("Phòng Ban");

        jLabel4.setText("Loại Nhân Viên");

        jLabel5.setText("Lương Cơ Bản");

        jLabel6.setText("Doanh Số");

        jLabel7.setText("Hoa Hồng");

        jLabel8.setText("Lương Trách Nhiệm");

        cb_pb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PB001", "PB002", "PB003", "PB004", "PB005", "PB006" }));

        cb_loai_nv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hành Chính", "Tiếp Thị", "Trưởng Phòng" }));
        cb_loai_nv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_loai_nvActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 102));
        jLabel9.setText("Nhân Viên ISOLF");

        tf_tk.setToolTipText("nhập mã nhân viên để tìm");

        jButton6.setText("Hiển Thị");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Xóa DL");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/1.jpg"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/2.jpg"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/3.jpg"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/4.jpg"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(305, 305, 305))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_manv)
                            .addComponent(tf_hoten)
                            .addComponent(cb_pb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_loai_nv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_lcb)
                            .addComponent(tf_ds)
                            .addComponent(tf_hh)
                            .addComponent(tf_ltn, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jButton8)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10)
                        .addGap(18, 18, 18)
                        .addComponent(jButton11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_tk, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton7))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(tf_lcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(tf_manv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1)
                                .addComponent(jButton6)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(tf_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_ds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(cb_pb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_hh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(cb_loai_nv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_ltn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(tf_tk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        themNhanVien();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        suaNhanVien();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        xoaNhanVien();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        sapXepTheoLuongTangDan();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        timKiemTheoMa();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tbNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNVMouseClicked
        // TODO add your handling code here:
        hienThiThongTinLenForm();
    }//GEN-LAST:event_tbNVMouseClicked

    private void cb_loai_nvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_loai_nvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_loai_nvActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        tbNV.setRowSelectionInterval(0, 0);
        hienThiThongTinLenForm();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        tbNV.setRowSelectionInterval(tbNV.getRowCount() - 1, tbNV.getRowCount() - 1);
        hienThiThongTinLenForm();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int n = tbNV.getSelectedRow();
        if (n > 0) {
            tbNV.setRowSelectionInterval(n - 1, n - 1);
        } else {
            tbNV.setRowSelectionInterval(tbNV.getRowCount() - 1, tbNV.getRowCount() - 1);
        }
        hienThiThongTinLenForm();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        int n = tbNV.getSelectedRow();
        if (n == tbNV.getRowCount() - 1) {
            tbNV.setRowSelectionInterval(0, 0);
        } else {
            tbNV.setRowSelectionInterval(n + 1, n + 1);
        }
        hienThiThongTinLenForm();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        hienThiDanhSachNhanVien();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Refresh();

    }//GEN-LAST:event_jButton7ActionPerformed
    public void Refresh()
    {
        tf_manv.setText("");
        tf_hoten.setText("");
        cb_pb.setSelectedIndex(0);
        cb_loai_nv.setSelectedIndex(0);
        tf_lcb.setText("");
        tf_hh.setText("");
        tf_ds.setText("");
        tf_ltn.setText("");
    }
    public void xuLyLoaiNhanVien() {
        String loai = cb_loai_nv.getSelectedItem().toString();
        if (loai.equalsIgnoreCase("Tiếp thị")) {
            tf_ds.setEnabled(true);
            tf_hh.setEnabled(true);
            tf_ltn.setText("");
            tf_ltn.setEnabled(false);
        } else if (loai.equalsIgnoreCase("Hành chính")) {
            tf_ds.setText("");
            tf_hh.setText("");
            tf_ltn.setText("");

            tf_ds.setEnabled(false);
            tf_hh.setEnabled(false);
            tf_ltn.setEnabled(false);
        } else if (loai.equalsIgnoreCase("Trưởng phòng")) {
            tf_ds.setText("");
            tf_hh.setText("");
            tf_ds.setEnabled(false);
            tf_hh.setEnabled(false);
            tf_ltn.setEnabled(true);
        }
    }

    public boolean kiemTraThongTinTheoLoai() {
        String loai = cb_loai_nv.getSelectedItem().toString();

        if (loai.equalsIgnoreCase("Tiếp thị")) {
            if (tf_ds.getText().trim().isEmpty() || tf_hh.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ Doanh số và Hoa hồng cho nhân viên Tiếp thị.");
                return false;
            }
        } else if (loai.equalsIgnoreCase("Trưởng phòng")) {
            if (tf_ltn.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập Lương trách nhiệm cho Trưởng phòng.");
                return false;
            }
        }

        return true;
    }

    public void hienThiThongTinLenForm() {
        int row = tbNV.getSelectedRow();
        if (row == -1) {
            return; // chưa chọn dòng nào
        }
        String ma = tbNV.getValueAt(row, 0).toString();
        String ten = tbNV.getValueAt(row, 1).toString();
        String phong = tbNV.getValueAt(row, 2).toString();
        String loai = tbNV.getValueAt(row, 3).toString();
        String lcbStr = tbNV.getValueAt(row, 4).toString();

        tf_manv.setText(ma);
        tf_hoten.setText(ten);
        for (int i = 0; i < cb_pb.getItemCount(); i++) {
            String item = cb_pb.getItemAt(i).toString().trim();
            if (item.equalsIgnoreCase(phong.trim())) {
                cb_pb.setSelectedIndex(i);
                break;
            }
        }
        for (int i = 0; i < cb_loai_nv.getItemCount(); i++) {
            String item = cb_loai_nv.getItemAt(i).toString().trim();
            if (item.equalsIgnoreCase(loai.trim())) {
                cb_loai_nv.setSelectedIndex(i);
                break;
            }
        }

        tf_lcb.setText(lcbStr);

        // Xử lý các trường riêng theo loại nhân viên
        if (loai.equalsIgnoreCase("Tiếp Thị")) {
            tf_ds.setText(tbNV.getValueAt(row, 5) != null ? tbNV.getValueAt(row, 5).toString() : "");
            tf_hh.setText(tbNV.getValueAt(row, 6) != null ? tbNV.getValueAt(row, 6).toString() : "");
            tf_ltn.setText(""); // không có
        } else if (loai.equalsIgnoreCase("Trưởng phòng")) {
            tf_ltn.setText(tbNV.getValueAt(row, 7) != null ? tbNV.getValueAt(row, 7).toString() : "");
            tf_ds.setText("");
            tf_hh.setText("");
        } else {
            tf_ds.setText("");
            tf_hh.setText("");
            tf_ltn.setText("");
        }
    }

    public void hienThiDanhSachNhanVien(List<Nhanvien> list) {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{
            "Mã NV", "Họ tên", "Phòng", "Loại", "Lương CB", "Doanh số", "Hoa hồng", "Lương TN"
        });

        for (Nhanvien nv : list) {
            if (nv instanceof NhanVienTiepThi tt) {
                model.addRow(new Object[]{
                    tt.getMaNV(), tt.getHoTen(), tt.getPhongBan(), "Tiếp thị", tt.getLuongCoBan(),
                    tt.getDoanhSo(), tt.getHoaHong(), null
                });
            } else if (nv instanceof TruongPhong tp) {
                model.addRow(new Object[]{
                    tp.getMaNV(), tp.getHoTen(), tp.getPhongBan(), "Trưởng phòng", tp.getLuongCoBan(),
                    null, null, tp.getLuongTrachNhiem()
                });
            } else {
                model.addRow(new Object[]{
                    nv.getMaNV(), nv.getHoTen(), nv.getPhongBan(), "Hành chính", nv.getLuongCoBan(),
                    null, null, null
                });
            }
        }

        tbNV.setModel(model);
    }

    public void hienThiDanhSachNhanVien() {
        try {
            NhanVienDAO dao = new NhanVienDAO();
            List<Nhanvien> list = dao.getAll();

            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new String[]{
                "Mã NV", "Họ tên", "Phòng ban", "Loại NV", "Lương CB", "Doanh số", "Hoa hồng", "Lương trách nhiệm"
            });

            for (Nhanvien nv : list) {
                if (nv instanceof NhanVienTiepThi) {
                    NhanVienTiepThi tt = (NhanVienTiepThi) nv;
                    model.addRow(new Object[]{
                        tt.getMaNV(), tt.getHoTen(), tt.getPhongBan(), "Tiếp thị", tt.getLuongCoBan(),
                        tt.getDoanhSo(), tt.getHoaHong(), null
                    });
                } else if (nv instanceof TruongPhong) {
                    TruongPhong tp = (TruongPhong) nv;
                    model.addRow(new Object[]{
                        tp.getMaNV(), tp.getHoTen(), tp.getPhongBan(), "Trưởng phòng", tp.getLuongCoBan(),
                        null, null, tp.getLuongTrachNhiem()
                    });
                } else if (nv instanceof NhanVienHanhChinh) {
                    model.addRow(new Object[]{
                        nv.getMaNV(), nv.getHoTen(), nv.getPhongBan(), "Hành chính", nv.getLuongCoBan(),
                        null, null, null
                    });
                }
            }

            tbNV.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi hiển thị nhân viên");
        }
    }

    public void themNhanVien() {
        try {

            String ma = tf_manv.getText();
            String ten = tf_hoten.getText();
            String pb = cb_pb.getSelectedItem().toString();
            String loai = cb_loai_nv.getSelectedItem().toString();
            double lcb = Double.parseDouble(tf_lcb.getText());

            Nhanvien nv = null;
            if (!kiemTraThongTinTheoLoai()) {
                return;
            }

            if (loai.equals("Hành chính")) {
                nv = new NhanVienHanhChinh(ma, ten, pb, lcb);
            } else if (loai.equals("Tiếp thị")) {
                double ds = Double.parseDouble(tf_ds.getText());
                double hh = Double.parseDouble(tf_hh.getText());
                nv = new NhanVienTiepThi(ma, ten, pb, lcb, ds, hh);
            } else if (loai.equals("Trưởng phòng")) {
                double tn = Double.parseDouble(tf_ltn.getText());
                nv = new TruongPhong(ma, ten, pb, lcb, tn);
            }

            new NhanVienDAO().insert(nv);
            hienThiDanhSachNhanVien();
            JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi thêm nhân viên: " + e.getMessage());
        }
    }

    public void suaNhanVien() {
        try {
            String ma = tf_manv.getText();
            String ten = tf_hoten.getText();
            String pb = cb_pb.getSelectedItem().toString();
            String loai = cb_loai_nv.getSelectedItem().toString();
            double lcb = Double.parseDouble(tf_lcb.getText());

            Nhanvien nv = null;

            if (loai.equalsIgnoreCase("Hành chính")) {
                nv = new NhanVienHanhChinh(ma, ten, pb, lcb);
            } else if (loai.equalsIgnoreCase("Tiếp thị")) {
                double ds = Double.parseDouble(tf_ds.getText());
                double hh = Double.parseDouble(tf_hh.getText());
                nv = new NhanVienTiepThi(ma, ten, pb, lcb, ds, hh);
            } else if (loai.equalsIgnoreCase("Trưởng phòng")) {
                double tn = Double.parseDouble(tf_ltn.getText());
                nv = new TruongPhong(ma, ten, pb, lcb, tn);
            }
            /*
            if (nv == null) {
                JOptionPane.showMessageDialog(this, "Loại nhân viên không hợp lệ hoặc chưa được chọn!");
                return;
            }
             */
            new NhanVienDAO().update(nv);
            hienThiDanhSachNhanVien();
            JOptionPane.showMessageDialog(this, "Cập nhật nhân viên thành công!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi sửa nhân viên: " + e.getMessage());
        }
    }

    public void xoaNhanVien() {
        String ma = tf_manv.getText();
        try {
            if (new NhanVienDAO().delete(ma)) {
                hienThiDanhSachNhanVien();
                JOptionPane.showMessageDialog(this, "Xoá nhân viên thành công!");
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy mã nhân viên cần xoá.");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi xoá nhân viên: " + e.getMessage());
        }
    }

    public void timKiemTheoMa() {
        String ma = tf_tk.getText();
        try {
            Nhanvien nv = new NhanVienDAO().findById(ma);
            if (nv != null) {
                List<Nhanvien> list = new ArrayList<>();
                list.add(nv);
                hienThiDanhSachNhanVien(list);
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên!");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi tìm kiếm: " + e.getMessage());
        }
    }

    public void sapXepTheoLuongTangDan() {
        try {
            List<Nhanvien> list = new NhanVienDAO().getAll();
            list.sort(Comparator.comparingDouble(Nhanvien::getLuongCoBan));
            hienThiDanhSachNhanVien(list);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi sắp xếp: " + e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_loai_nv;
    private javax.swing.JComboBox<String> cb_pb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbNV;
    private javax.swing.JTextField tf_ds;
    private javax.swing.JTextField tf_hh;
    private javax.swing.JTextField tf_hoten;
    private javax.swing.JTextField tf_lcb;
    private javax.swing.JTextField tf_ltn;
    private javax.swing.JTextField tf_manv;
    private javax.swing.JTextField tf_tk;
    // End of variables declaration//GEN-END:variables
}
