/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import DAO.Connection_Isolf;
import DAO.PhongBanDAO;
import Model.PhongBan;
import Model.User;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yuuki
 */
public class PhongBanPanel extends javax.swing.JPanel {

    /**
     * Creates new form pb_panel
     */
    private User currentUser;

    public PhongBanPanel(User user) {
        this.currentUser = user;
        initComponents();
        phanQuyenTheoVaiTro();
        hienThiDanhSachPhongBan();
    }

    public void hienThiDanhSachPhongBan() {
        try {
            List<PhongBan> list = new PhongBanDAO().getAllPhongBan();

            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new String[]{"Mã PB", "Tên phòng", "Mô tả"});

            for (PhongBan pb : list) {
                model.addRow(new Object[]{
                    pb.getMaPB(), pb.getTenPB(), pb.getMoTa()
                });
            }

            tbPB.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi hiển thị phòng ban");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPB = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_mapb = new javax.swing.JTextField();
        tf_tenpb = new javax.swing.JTextField();
        tf_mota = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        jButton5.setText("jButton1");

        jButton6.setText("jButton2");

        jButton7.setText("jButton3");

        jButton8.setText("jButton4");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/3.jpg"))); // NOI18N

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/4.jpg"))); // NOI18N

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/1.jpg"))); // NOI18N

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/2.jpg"))); // NOI18N

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbPB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Phòng Ban", "Tên Phòng Ban", "Mô Tả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbPB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPB);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 374, 721, 200));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 358, 721, 10));

        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });
        add(btThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 111, 84, -1));

        btSua.setText("Sửa");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });
        add(btSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 166, 84, -1));

        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });
        add(btXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 211, 84, -1));

        jButton12.setText("Hiển Thị Nhân Viên Phòng Ban");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 266, -1, -1));

        jLabel1.setText("Mã phòng ban");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 126, 101, -1));

        jLabel2.setText("Tên phòng ban");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 193, 101, -1));

        jLabel3.setText("Mô tả");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 249, 101, -1));
        add(tf_mapb, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 121, 158, -1));
        add(tf_tenpb, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 188, 158, -1));
        add(tf_mota, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 232, 266, 61));

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/3.jpg"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 311, -1, -1));

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/4.jpg"))); // NOI18N
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 311, -1, -1));

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/1.jpg"))); // NOI18N
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 311, -1, -1));

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/2.jpg"))); // NOI18N
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 311, -1, -1));

        jButton21.setText("Xóa DL");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 111, 78, -1));

        jButton22.setText("Hiển Thị");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 166, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/backpanel2.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
        themPhongBan();
    }//GEN-LAST:event_btThemActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        suaPhongBan();
    }//GEN-LAST:event_btSuaActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        xoaPhongBan();
    }//GEN-LAST:event_btXoaActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        hienThiSoLuongNhanVienTheoPhong();

    }//GEN-LAST:event_jButton12ActionPerformed

    private void tbPBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPBMouseClicked
        // TODO add your handling code here:
        hienThiThongTinLenFormPhongBan();
    }//GEN-LAST:event_tbPBMouseClicked

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        tbPB.setRowSelectionInterval(0, 0);
        hienThiThongTinLenFormPhongBan();
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        tbPB.setRowSelectionInterval(tbPB.getRowCount() - 1, tbPB.getRowCount() - 1);
        hienThiThongTinLenFormPhongBan();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        int n = tbPB.getSelectedRow();
        if (n > 0) {
            tbPB.setRowSelectionInterval(n - 1, n - 1);
        } else {
            tbPB.setRowSelectionInterval(tbPB.getRowCount() - 1, tbPB.getRowCount() - 1);
        }
        hienThiThongTinLenFormPhongBan();
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        int n = tbPB.getSelectedRow();
        if (n == tbPB.getRowCount() - 1) {
            tbPB.setRowSelectionInterval(0, 0);
        } else {
            tbPB.setRowSelectionInterval(n + 1, n + 1);
        }
        hienThiThongTinLenFormPhongBan();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        xoaFormPhongBan();
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        hienThiDanhSachPhongBan();
    }//GEN-LAST:event_jButton22ActionPerformed
    private void phanQuyenTheoVaiTro() {
        String role = currentUser.getRole().toLowerCase();

        if (role.equals("intern")) {
            btThem.setEnabled(false);
            btSua.setEnabled(false);
            btXoa.setEnabled(false);
        } else if (role.equals("hr")) {
            // OK
        } else if (role.equals("admin")) {
            // OK
        }
    }

    public void xoaFormPhongBan() {
        tf_mapb.setText("");
        tf_tenpb.setText("");
        tf_mota.setText("");
    }

    public void hienThiThongTinLenFormPhongBan() {
        int row = tbPB.getSelectedRow();
        if (row == -1) {
            return; // chưa chọn dòng
        }
        String ma = tbPB.getValueAt(row, 0).toString();
        String ten = tbPB.getValueAt(row, 1).toString();
        String moTa = tbPB.getValueAt(row, 2).toString();

        tf_mapb.setText(ma);
        tf_tenpb.setText(ten);
        tf_mota.setText(moTa);
    }

    public void themPhongBan() {
        try {
            String ma = tf_mapb.getText();
            String ten = tf_tenpb.getText();
            String moTa = tf_mota.getText();

            PhongBan pb = new PhongBan(ma, ten, moTa);
            new PhongBanDAO().addPhongBan(pb);
            hienThiDanhSachPhongBan();
            JOptionPane.showMessageDialog(this, "Thêm phòng ban thành công!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi thêm phòng ban: " + e.getMessage());
        }
    }

    public void suaPhongBan() {
        try {
            String ma = tf_mapb.getText();
            String ten = tf_tenpb.getText();
            String moTa = tf_mota.getText();

            PhongBan pb = new PhongBan(ma, ten, moTa);
            new PhongBanDAO().updatePhongBan(pb);
            hienThiDanhSachPhongBan();
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi cập nhật phòng ban: " + e.getMessage());
        }
    }

    public void xoaPhongBan() {
        try {
            String ma = tf_mapb.getText();
            new PhongBanDAO().deletePhongBan(ma);
            hienThiDanhSachPhongBan();
            JOptionPane.showMessageDialog(this, "Xoá thành công!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi xoá phòng ban: " + e.getMessage());
        }
    }

    public void hienThiSoLuongNhanVienTheoPhong() {
        try {
            Map<String, Integer> map = new PhongBanDAO().thongKeSoLuongNhanVienTheoPhong();

            StringBuilder result = new StringBuilder("Số lượng nhân viên theo phòng:\n");
            for (Map.Entry<String, Integer> entry : map.entrySet()) {
                result.append("Phòng ").append(entry.getKey())
                        .append(": ").append(entry.getValue()).append(" nhân viên\n");
            }

            JOptionPane.showMessageDialog(this, result.toString());
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi thống kê: " + e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tbPB;
    private javax.swing.JTextField tf_mapb;
    private javax.swing.JTextField tf_mota;
    private javax.swing.JTextField tf_tenpb;
    // End of variables declaration//GEN-END:variables
}
