/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import DAO.SinhVienDAO;
import Model.SinhVien;
import Model.User;
import java.util.Comparator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yuuki
 */
public class SinhVienPanel extends javax.swing.JPanel {

    private User currentUser;

    /**
     * Creates new form sv_panel
     */
    public SinhVienPanel(User user) {
        this.currentUser = user;
        initComponents();
        phanQuyenTheoVaiTro();
        hienThiDanhSachSinhVien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSV = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_masv = new javax.swing.JTextField();
        tf_hoten = new javax.swing.JTextField();
        tf_email = new javax.swing.JTextField();
        tf_cccd = new javax.swing.JTextField();
        cb_ptt = new javax.swing.JComboBox<>();
        tf_ddg = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_sdt = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        tf_tk = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jButton1.setText("Thêm");

        jButton2.setText("Sửa");

        jButton3.setText("Xóa");

        jButton4.setText("Sắp Xếp");

        jButton5.setText("Tìm Kiếm");

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/3.jpg"))); // NOI18N

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/4.jpg"))); // NOI18N

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/1.jpg"))); // NOI18N

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/2.jpg"))); // NOI18N

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sinh Viên", "Họ Tên", "Email", "SDT", "CCCD", "Phòng Thực Tập", "Điểm Đánh Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSV);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 372, 721, 200));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 351, 721, -1));

        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });
        add(btThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 84, -1));

        btSua.setText("Sửa");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });
        add(btSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 84, -1));

        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });
        add(btXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 84, -1));

        jButton9.setText("Sắp Xếp");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 84, -1));

        jButton10.setText("Tìm Kiếm");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 90, -1));

        jLabel1.setText("Mã sinh viên");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 99, 82, -1));

        jLabel2.setText("Họ tên");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 151, 82, -1));

        jLabel3.setText("Email");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 217, 82, -1));

        jLabel4.setText("CCCD");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 99, 89, -1));

        jLabel5.setText("Phòng thực tập");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 151, 89, -1));

        jLabel6.setText("Điểm đánh giá");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 217, 89, -1));
        add(tf_masv, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 94, 140, -1));
        add(tf_hoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 146, 140, -1));
        add(tf_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 212, 140, -1));
        add(tf_cccd, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 129, -1));

        cb_ptt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PB001", "PB002", "PB003", "PB004", "PB005", "PB006" }));
        add(cb_ptt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 129, -1));
        add(tf_ddg, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 129, -1));

        jLabel7.setText("SDT");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 276, -1, -1));
        add(tf_sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 271, 140, -1));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/3.jpg"))); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 290, -1, -1));

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/4.jpg"))); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 290, -1, -1));

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/1.jpg"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 290, -1, -1));

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/2.jpg"))); // NOI18N
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 290, -1, -1));
        add(tf_tk, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 129, -1));

        jLabel8.setText("Tìm theo mã hoặc tên");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 261, 120, -1));

        jButton21.setText("Xóa DL");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 90, -1));

        jButton22.setText("Hiển Thị");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 90, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/backpanel2 (1).png"))); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(800, 600));
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
        themSinhVien();
    }//GEN-LAST:event_btThemActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        suaSinhVien();
    }//GEN-LAST:event_btSuaActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        xoaSinhVien();
    }//GEN-LAST:event_btXoaActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        sapXepTheoDiemTang();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        timKiemSinhVien();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void tbSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSVMouseClicked
        // TODO add your handling code here:
        hienThiThongTinSinhVienLenForm();
    }//GEN-LAST:event_tbSVMouseClicked

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        tbSV.setRowSelectionInterval(0, 0);
        hienThiThongTinSinhVienLenForm();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        tbSV.setRowSelectionInterval(tbSV.getRowCount() - 1, tbSV.getRowCount() - 1);
        hienThiThongTinSinhVienLenForm();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        int n = tbSV.getSelectedRow();
        if (n > 0) {
            tbSV.setRowSelectionInterval(n - 1, n - 1);
        } else {
            tbSV.setRowSelectionInterval(tbSV.getRowCount() - 1, tbSV.getRowCount() - 1);
        }
        hienThiThongTinSinhVienLenForm();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        int n = tbSV.getSelectedRow();
        if (n == tbSV.getRowCount() - 1) {
            tbSV.setRowSelectionInterval(0, 0);
        } else {
            tbSV.setRowSelectionInterval(n + 1, n + 1);
        }
        hienThiThongTinSinhVienLenForm();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        xoaFormSinhVien();
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        hienThiDanhSachSinhVien();
    }//GEN-LAST:event_jButton22ActionPerformed

    public void xoaFormSinhVien() {
        tf_masv.setText("");
        tf_hoten.setText("");
        tf_email.setText("");
        tf_cccd.setText("");
        tf_ddg.setText("");
        cb_ptt.setSelectedIndex(0);
    }

    public void hienThiThongTinSinhVienLenForm() {
        int row = tbSV.getSelectedRow();
        if (row == -1) {
            return; // nếu chưa chọn dòng nào
        }
        String ma = tbSV.getValueAt(row, 0).toString();
        String ten = tbSV.getValueAt(row, 1).toString();
        String email = tbSV.getValueAt(row, 2).toString();
        String sdt = tbSV.getValueAt(row, 3).toString();
        String cccd = tbSV.getValueAt(row, 4).toString();
        String phong = tbSV.getValueAt(row, 5).toString();
        String diem = tbSV.getValueAt(row, 6).toString();

        tf_masv.setText(ma);
        tf_hoten.setText(ten);
        tf_email.setText(email);
        tf_sdt.setText(sdt);
        tf_cccd.setText(cccd);
        tf_ddg.setText(diem);
        cb_ptt.setSelectedItem(phong);
    }

    private void phanQuyenTheoVaiTro() {
        if (currentUser.getRole().equalsIgnoreCase("intern")) {
            btThem.setEnabled(false);
            btSua.setEnabled(false);
            btXoa.setEnabled(false);

            // Nếu dùng menu hoặc table editable, disable luôn
            tbSV.setEnabled(true); // vẫn cho chọn
        }
    }

    public void hienThiDanhSachSinhVien() {
        try {
            SinhVienDAO dao = new SinhVienDAO();
            List<SinhVien> list = dao.getAllSinhVien(); // lấy toàn bộ danh sách

            // Tạo model cho bảng
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new String[]{
                "Mã SV", "Họ tên", "Email", "SĐT", "CMND", "Phòng TT", "Điểm ĐG"
            });

            // Đổ dữ liệu từ list vào model
            for (SinhVien sv : list) {
                model.addRow(new Object[]{
                    sv.getMaSV(),
                    sv.getHoTen(),
                    sv.getEmail(),
                    sv.getSdt(),
                    sv.getCmnd(),
                    sv.getPhongThucTap(),
                    sv.getDiemDanhGia()
                });
            }

            // Gán model vào bảng
            tbSV.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi hiển thị danh sách sinh viên");
        }
    }

    public void hienThiDanhSachSinhVien(List<SinhVien> list) {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{
            "Mã SV", "Họ tên", "Email", "SĐT", "CMND", "Phòng TT", "Điểm ĐG"
        });

        for (SinhVien sv : list) {
            model.addRow(new Object[]{
                sv.getMaSV(), sv.getHoTen(), sv.getEmail(),
                sv.getSdt(), sv.getCmnd(), sv.getPhongThucTap(), sv.getDiemDanhGia()
            });
        }

        tbSV.setModel(model);
    }

    public void themSinhVien() {
        try {
            String ma = tf_masv.getText();
            String ten = tf_hoten.getText();
            String email = tf_email.getText();
            String sdt = tf_sdt.getText();
            String cmnd = tf_cccd.getText();
            String ptt = cb_ptt.getSelectedItem().toString();
            double ddg = Double.parseDouble(tf_ddg.getText());

            SinhVien sv = new SinhVien(ma, ten, email, sdt, cmnd, ptt, ddg);
            new SinhVienDAO().addSinhVien(sv);
            hienThiDanhSachSinhVien();
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi thêm sinh viên: " + e.getMessage());
        }
    }

    public void suaSinhVien() {
        try {
            String ma = tf_masv.getText();
            String ten = tf_hoten.getText();
            String email = tf_email.getText();
            String sdt = tf_sdt.getText();
            String cmnd = tf_cccd.getText();
            String ptt = cb_ptt.getSelectedItem().toString();
            double ddg = Double.parseDouble(tf_ddg.getText());

            SinhVien sv = new SinhVien(ma, ten, email, sdt, cmnd, ptt, ddg);
            new SinhVienDAO().updateSinhVien(sv);
            hienThiDanhSachSinhVien();
            JOptionPane.showMessageDialog(this, "Sửa thành công!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi sửa sinh viên: " + e.getMessage());
        }
    }

    public void xoaSinhVien() {
        try {
            String ma = tf_masv.getText();
            new SinhVienDAO().deleteSinhVien(ma);
            hienThiDanhSachSinhVien();
            JOptionPane.showMessageDialog(this, "Xoá thành công!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi xoá sinh viên: " + e.getMessage());
        }
    }

    public void timKiemSinhVien() {
        try {
            String keyword = tf_tk.getText(); // có thể tạo tf_tim_ma nếu cần riêng
            List<SinhVien> list = new SinhVienDAO().searchSinhVien(keyword);
            hienThiDanhSachSinhVien(list);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi tìm kiếm: " + e.getMessage());
        }
    }

    public void sapXepTheoDiemTang() {
        try {
            List<SinhVien> list = new SinhVienDAO().getAllSinhVien();
            list.sort(Comparator.comparingDouble(SinhVien::getDiemDanhGia)); // tăng dần
            hienThiDanhSachSinhVien(list);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi sắp xếp: " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btXoa;
    private javax.swing.JComboBox<String> cb_ptt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbSV;
    private javax.swing.JTextField tf_cccd;
    private javax.swing.JTextField tf_ddg;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_hoten;
    private javax.swing.JTextField tf_masv;
    private javax.swing.JTextField tf_sdt;
    private javax.swing.JTextField tf_tk;
    // End of variables declaration//GEN-END:variables
}
